### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by tnt1094** [Zahariel1942/D2Stats#1]
it can be fixed? it displays the name of items completely where unnecessary and not specified flag name, also it can not work correctly with color flags for example umo red but takes and displays the real color
![Screenshot_4](https://github.com/Zahariel1942/D2Stats/assets/140633894/c7984c95-c34f-4292-b5d0-3c6c99f33f17)
![Screenshot_2](https://github.com/Zahariel1942/D2Stats/assets/140633894/063886ed-53be-4bd6-b545-c3b3bbb2a179)

**Comment by Zahariel1942** [comment]
resolve at cab918d
