### ISSUE TITLE
File name for release

### ISSUE THREAD

**Issue by Thorinori** [Zahariel1942/D2Stats#5]
Would it be possible to revert the version from the zip file name commit? Currently making a PR for d2launcher and ideally wanted to use https://github.com/Zahariel1942/D2Stats/releases/latest/download/D2Stats.zip to pull the most recent version, but having the version in the file name makes that a decent bit harder to do.

**Comment by Zahariel1942** [comment]
Apologies for the inconvenience. The issue will be addressed in the NEXT release.
