### ISSUE TITLE
Feature Request: Ability to turn off Unique Base names

### ISSUE THREAD

**Issue by ChandlerFerry** [Zahariel1942/D2Stats#6]
Current: `{SSU} Balanced Axe (Sacred) Ophiophagus`
Filter Line: `unique name`

Desired: `{SSU} Ophiophagus`

**Comment by Zahariel1942** [comment]
This could cause confusion as many people use the "Balanced Axe" text as a filtering condition. Perhaps introducing a toggle or flag could resolve the issue. Further discussion is needed.

**Comment by synonymouse** [comment]
In the next major version, it will look like this. And with this style, I think there's no point in completely hiding the item type. Everything is already maximally readable. I don't really want to add a separate flag for every little thing.

![image](https://github.com/Zahariel1942/D2Stats/assets/13904950/2a40710e-ebc7-48fa-be1a-7d4ef0f6595d)
