### ISSUE TITLE
Feature Request: Trigger on Certain Stat

### ISSUE THREAD

**Issue by altoiddealer** [Zahariel1942/D2Stats#7]
Hello, I love the addition of the stat parameter to display all the stats of the item.

What would be extremely useful is a means to only trigger for a certain stat.

Example to illustrate the concept:
"Ring$" rare stat(+1 to All Skills)

Just wishful thinking.  Thanks!

**Comment by Zahariel1942** [comment]
I like this idea as well. I'll implement it when I have some free time.

**Comment by synonymouse** [comment]
This feature will be added in the next major version soon
