### ISSUE TITLE
Feature Request: Include # Sockets when using "stat"

### ISSUE THREAD

**Issue by altoiddealer** [Zahariel1942/D2Stats#8]
Hello, I said this in my other request and I'll say it again - the Stat attribute is really awesome, thanks for adding this.

I'm suggesting to include the # of sockets at the end of the description.

sacred eth superior stat

Currently:
(Eth) Diadem (Sacred) Physical Resist 1% +44% Enhanced Defense

Suggested change with (sockets) at the end
(Eth) Diadem (Sacred) Physical Resist 1% +44% Enhanced Defense (4)

**Comment by Zahariel1942** [comment]
see eb521537a60ea6dd4a6fcb5f6858b7ab0432863d

**Comment by synonymouse** [comment]
https://github.com/Zahariel1942/D2Stats/releases/tag/4.0.1
